about:
  summary: "MULTIPLY pre processing package"
  home: https://github.com/multiply-org/pre_processing

package:
  name: multiply-pre-processing
  version: "0.1"

source:
  git_url: "https://github.com/multiply-org/pre_processing.git"

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
